apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-volume
  labels:
    type: local
spec:
  storageClassName: influx-volume
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influx"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-volume
spec:
  storageClassName: influx-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: influx-svc
  labels:
    app: influx
spec:
  selector:
    app: influx
  type: ClusterIP
  ports:
    - protocol: TCP
      name: influx
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-dpl
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      volumes:
      - name: influx-volume
        persistentVolumeClaim:
          claimName: influx-volume
      containers:
      - name: influx
        image: influx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influx-volume
          mountPath: /var/lib/