apiVersion: v1
kind: Service
metadata:
  name: pma-svc
spec:
  selector:
    app: pma-deployment
  # loadBalancerIP: 192.168.99.130
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: pma
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-dpl
  labels:
    app: pma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: pma_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000