apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.110
  ports:
    - protocol: TCP
      name: activ
      port: 21
      targetPort: 21
      nodePort: 21
    - protocol: TCP
      name: pasiv
      port: 21210
      targetPort: 21210
      nodePort: 21210
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dpl
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21210